In [1]:
import pandas as pd
import numpy as np

## 1. Extraction

In [2]:
# load dataset
df = pd.read_csv("../data/covid_2020.csv")
df.head()

,Row_ID,Accurate_Episode_Date,Case_Reported_Date,Test_Reported_Date,Specimen_Date,Age_Group,Client_Gender,Outcome1,Reporting_PHU_ID,Reporting_PHU,Reporting_PHU_Address,Reporting_PHU_City,Reporting_PHU_Postal_Code,Reporting_PHU_Website,Reporting_PHU_Latitude,Reporting_PHU_Longitude,case_reported_date_column_in_years
0,9,2019-05-30,2020-05-05,2020-05-05,2020-05-03,50s,FEMALE,NaN,2260,Simcoe Muskoka District Health Unit,15 Sperling Drive,Barrie,L4M 6K9,www.simcoemuskokahealth.org,44.410713,-79.686306,2020-05-05
1,10,2019-11-20,2020-10-21,2020-11-21,2019-11-20,20s,FEMALE,NaN,4913,Southwestern Public Health,1230 Talbot Street,St. Thomas,N5P 1G9,www.swpublichealth.ca,42.777804,-81.151156,2020-10-21
2,12,2020-01-01,2020-04-24,2020-04-24,2020-04-23,80s,MALE,NaN,2234,Haldimand-Norfolk Health Unit,12 Gilbertson Drive,Simcoe,N3Y 4N5,www.hnhu.org,42.847825,-80.303815,2020-04-24
3,13,2020-01-01,2020-05-17,2020-05-17,2020-05-15,50s,MALE,NaN,2265,"Region of Waterloo, Public Health",99 Regina Street South,Waterloo,N2J 4V3,www.regionofwaterloo.ca,43.462876,-80.520913,2020-05-17
4,14,2020-01-10,2020-06-10,2020-06-10,2020-06-09,50s,MALE,NaN,2234,Haldimand-Norfolk Health Unit,12 Gilbertson Drive,Simcoe,N3Y 4N5,www.hnhu.org,42.847825,-80.303815,2020-06-10

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 187795 entries, 0 to 187794
Data columns (total 17 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Row_ID                              187795 non-null  int64
 1   Accurate_Episode_Date               187795 non-null  str
 2   Case_Reported_Date                  187795 non-null  str
 3   Test_Reported_Date                  184082 non-null  str
 4   Specimen_Date                       186838 non-null  str
 5   Age_Group                           187795 non-null  str
 6   Client_Gender                       187795 non-null  str
 7   Outcome1                            5398 non-null    str
 8   Reporting_PHU_ID                    187795 non-null  int64
 9   Reporting_PHU                       187795 non-null  str
 10  Reporting_PHU_Address               187795 non-null  str
 11  Reporting_PHU_City                  187795 non-null  str
 12  Reporting_PHU_Postal_Code           187795 non-null  str
 13  Reporting_PHU_Website               187795 non-null  str
 14  Reporting_PHU_Latitude              187795 non-null  float64
 15  Reporting_PHU_Longitude             187795 non-null  float64
 16  case_reported_date_column_in_years  187795 non-null  str
dtypes: float64(2), int64(2), str(13)
memory usage: 24.4 MB

In [4]:
# check null values
df.isnull().sum()

Row_ID                                     0
Accurate_Episode_Date                      0
Case_Reported_Date                         0
Test_Reported_Date                      3713
Specimen_Date                            957
Age_Group                                  0
Client_Gender                              0
Outcome1                              182397
Reporting_PHU_ID                           0
Reporting_PHU                              0
Reporting_PHU_Address                      0
Reporting_PHU_City                         0
Reporting_PHU_Postal_Code                  0
Reporting_PHU_Website                      0
Reporting_PHU_Latitude                     0
Reporting_PHU_Longitude                    0
case_reported_date_column_in_years         0
dtype: int64

## 2. Transform

In [5]:
# standardize column names
df.columns = df.columns.str.lower()

In [6]:
# handle missing values
df["test_reported_date"] = df["test_reported_date"].fillna("UNKNOWN")
df["specimen_date"] = df["specimen_date"].fillna("UNKNOWN")
df["outcome1"] = df["outcome1"].fillna("NON-FATAL")

In [7]:
df.head()

,row_id,accurate_episode_date,case_reported_date,test_reported_date,specimen_date,age_group,client_gender,outcome1,reporting_phu_id,reporting_phu,reporting_phu_address,reporting_phu_city,reporting_phu_postal_code,reporting_phu_website,reporting_phu_latitude,reporting_phu_longitude,case_reported_date_column_in_years
0,9,2019-05-30,2020-05-05,2020-05-05,2020-05-03,50s,FEMALE,NON-FATAL,2260,Simcoe Muskoka District Health Unit,15 Sperling Drive,Barrie,L4M 6K9,www.simcoemuskokahealth.org,44.410713,-79.686306,2020-05-05
1,10,2019-11-20,2020-10-21,2020-11-21,2019-11-20,20s,FEMALE,NON-FATAL,4913,Southwestern Public Health,1230 Talbot Street,St. Thomas,N5P 1G9,www.swpublichealth.ca,42.777804,-81.151156,2020-10-21
2,12,2020-01-01,2020-04-24,2020-04-24,2020-04-23,80s,MALE,NON-FATAL,2234,Haldimand-Norfolk Health Unit,12 Gilbertson Drive,Simcoe,N3Y 4N5,www.hnhu.org,42.847825,-80.303815,2020-04-24
3,13,2020-01-01,2020-05-17,2020-05-17,2020-05-15,50s,MALE,NON-FATAL,2265,"Region of Waterloo, Public Health",99 Regina Street South,Waterloo,N2J 4V3,www.regionofwaterloo.ca,43.462876,-80.520913,2020-05-17
4,14,2020-01-10,2020-06-10,2020-06-10,2020-06-09,50s,MALE,NON-FATAL,2234,Haldimand-Norfolk Health Unit,12 Gilbertson Drive,Simcoe,N3Y 4N5,www.hnhu.org,42.847825,-80.303815,2020-06-10

## 3. Load

In [8]:
import os
from dotenv import load_dotenv

load_dotenv()

True

In [9]:
# read credentials
from urllib.parse import quote_plus
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = quote_plus(os.getenv("DB_PASSWORD"))
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")

In [10]:
# connect to postgres
from sqlalchemy import create_engine, text
engine = create_engine(f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}")

In [64]:
# create schema
with open("../sql/01_create_schema.sql", "r") as file:
    sql_script = file.read()
with engine.begin() as conn:
    conn.execute(text(sql_script))

In [11]:
# load data into postgres
df.to_sql("covid_cases", 
          engine, 
          if_exists="replace",
          index=False,
          chunksize=20000,
          method="multi")

187795